server:
  image:
    repository: quay.io/eformat/prelude-server
    tag: latest
  clusterPool: ""
  clusterLifetime: "2h"
  kubeconfigSecret: ""
  recaptchaSiteKey: ""
  recaptchaSecretKey: ""
  adminPassword: ""

clusterClaimer:
  image:
    repository: quay.io/eformat/prelude-cluster-claimer
    tag: latest
  clusterClaimLimit: "4"
  clusterClaimMax: "10"
  clusterClaimIncrement: "1"

clusterAuthenticator:
  image:
    repository: quay.io/eformat/prelude-cluster-authenticator
    tag: latest
  maasUrl: ""
  maasToken: ""

client:
  image:
    repository: quay.io/eformat/prelude-client
    tag: latest

route:
  host: ""
