server:
  image:
    repository: quay.io/eformat/prelude-server
    tag: latest
  clusterPool: ""
  clusterLifetime: "2h"
  kubeconfigSecret: ""
  recaptchaSiteKey: ""
  recaptchaSecretKey: ""

clusterClaimer:
  image:
    repository: quay.io/eformat/prelude-cluster-claimer
    tag: latest
  clusterClaimLimit: "4"

client:
  image:
    repository: quay.io/eformat/prelude-client
    tag: latest

route:
  host: ""
