replicas: 1

server:
  image:
    repository: quay.io/eformat/prelude-server
    tag: latest
  clusterPool: ""
  clusterLifetime: "2h"
  kubeconfigSecret: ""
  recaptchaSiteKey: ""
  recaptchaSecretKey: ""
  adminPassword: ""
  hideKubeconfig: true
  maasUrl: ""
  maasToken: ""
  chatbotConfig: |
    {
        "system_template": "You are a helpful, knowledgeable, and friendly assistant having a conversation with a human. Respond clearly, concisely, and accurately to user questions and requests. Adapt your tone to match the user's styleâ€”professional, casual, or otherwise. If clarification is needed, ask thoughtful follow-up questions. When appropriate, offer examples, summaries, or step-by-step guidance. Do not make up information; if you are unsure, say so. Be polite, nonjudgmental, and always aim to provide useful, easy-to-understand responses. Give your answer in {language} only, but don't translate any code. If your answer is not in English, don't give the English translation. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.",
        "translate_system_template": "Translate the following text to English. Translate the text as concisely as possible. Don't add any comment or information. If the text is already in English, don't modify it, just copy it without any other mention.",
        "llms": [
            {
                "name": "Granite-vision-3.2-2b",
                "model_name": "granite-vision-32-2b",
                "max_tokens": 65000,
                "temperature": 0.01,
                "top_p": 0.95,
                "presence_penalty": 1.03,
                "supports_vision": true
            },
            {
                "name": "Qwen2.5-VL-7B-Instruct-FP8-Dynamic",
                "model_name": "qwen25-vl-7b-instruct-fp8",
                "max_tokens": 55000,
                "temperature": 0.01,
                "top_p": 0.95,
                "presence_penalty": 1.03,
                "supports_vision": true
            },
            {
                "name": "Llama-4-Scout-17B-16E-W4A16",
                "model_name": "llama-4-scout-17b-16e-w4a16",
                "max_tokens": 350000,
                "temperature": 0.01,
                "top_p": 0.95,
                "presence_penalty": 1.03,
                "supports_vision": true
            }
        ]
    }

clusterClaimer:
  image:
    repository: quay.io/eformat/prelude-cluster-claimer
    tag: latest
  clusterClaimLimit: "4"
  clusterClaimMax: "10"
  clusterClaimIncrement: "1"
  clusterClaimAvailableThreshold: "1"

clusterAuthenticator:
  image:
    repository: quay.io/eformat/prelude-cluster-authenticator
    tag: latest
  keycloakUrl: ""
  keycloakClientSecret: ""

client:
  image:
    repository: quay.io/eformat/prelude-client
    tag: latest

route:
  host: ""

metrics:
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels: {}
  dashboard:
    enabled: true
    odc: false
