replicas: 1

server:
  image:
    repository: quay.io/eformat/prelude-server
    tag: latest
  clusterPool: ""
  clusterLifetime: "2h"
  kubeconfigSecret: ""
  recaptchaSiteKey: ""
  recaptchaSecretKey: ""
  adminPassword: ""
  maasUrl: ""
  maasToken: ""

clusterClaimer:
  image:
    repository: quay.io/eformat/prelude-cluster-claimer
    tag: latest
  clusterClaimLimit: "4"
  clusterClaimMax: "10"
  clusterClaimIncrement: "1"
  clusterClaimAvailableThreshold: "1"

clusterAuthenticator:
  image:
    repository: quay.io/eformat/prelude-cluster-authenticator
    tag: latest

client:
  image:
    repository: quay.io/eformat/prelude-client
    tag: latest

route:
  host: ""

metrics:
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
    labels: {}
  dashboard:
    enabled: true
    odc: false
