apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "prelude.fullname" . }}
  labels:
    {{- include "prelude.labels" . | nindent 4 }}
rules:
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterdeployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterclaims"]
    verbs: ["get", "list", "watch", "create", "update"]
  - apiGroups: ["hive.openshift.io"]
    resources: ["clusterpools"]
    verbs: ["get", "patch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["k8s.keycloak.org"]
    resources: ["keycloakrealmimports"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
