apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prelude.fullname" . }}
  labels:
    {{- include "prelude.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "prelude.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prelude.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "prelude.fullname" . }}
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy | default "Always" }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: HOSTNAME
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: production
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          imagePullPolicy: {{ .Values.server.image.pullPolicy | default "Always" }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          env:
            {{- if .Values.server.kubeconfigSecret }}
            - name: KUBECONFIG
              value: /etc/prelude/kubeconfig/kubeconfig
            {{- end }}
            - name: CLUSTER_POOL
              value: "{{ .Values.server.clusterPool }}"
            - name: CLUSTER_LIFETIME
              value: "{{ .Values.server.clusterLifetime }}"
            {{- if .Values.server.recaptchaSiteKey }}
            - name: RECAPTCHA_SITE_KEY
              value: "{{ .Values.server.recaptchaSiteKey }}"
            {{- end }}
            {{- if .Values.server.recaptchaSecretKey }}
            - name: RECAPTCHA_SECRET_KEY
              value: "{{ .Values.server.recaptchaSecretKey }}"
            {{- end }}
            {{- if .Values.server.adminPassword }}
            - name: ADMIN_PASSWORD
              value: "{{ .Values.server.adminPassword }}"
            {{- end }}
            {{- if .Values.server.hideKubeconfig }}
            - name: HIDE_KUBECONFIG
              value: "true"
            {{- end }}
            {{- if .Values.server.maasUrl }}
            - name: MAAS_URL
              value: "{{ .Values.server.maasUrl }}"
            {{- end }}
            {{- if .Values.server.maasToken }}
            - name: MAAS_TOKEN
              value: "{{ .Values.server.maasToken }}"
            {{- end }}
            {{- if not .Values.clusterAuthenticator.createHtpassSecret }}
            - name: CREATE_HTPASS_SECRET
              value: "false"
            {{- end }}
          {{- if .Values.server.kubeconfigSecret }}
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/prelude/kubeconfig
              readOnly: true
          {{- end }}
        - name: cluster-claimer
          image: "{{ .Values.clusterClaimer.image.repository }}:{{ .Values.clusterClaimer.image.tag }}"
          imagePullPolicy: {{ .Values.clusterClaimer.image.pullPolicy | default "Always" }}
          env:
            {{- if .Values.server.kubeconfigSecret }}
            - name: KUBECONFIG
              value: /etc/prelude/kubeconfig/kubeconfig
            {{- end }}
            - name: CLUSTER_POOL
              value: "{{ .Values.server.clusterPool }}"
            - name: CLUSTER_CLAIM_LIMIT
              value: "{{ .Values.clusterClaimer.clusterClaimLimit }}"
            - name: CLUSTER_CLAIM_MAX
              value: "{{ .Values.clusterClaimer.clusterClaimMax }}"
            - name: CLUSTER_CLAIM_INCREMENT
              value: "{{ .Values.clusterClaimer.clusterClaimIncrement }}"
            - name: CLUSTER_CLAIM_AVAILABLE_THRESHOLD
              value: "{{ .Values.clusterClaimer.clusterClaimAvailableThreshold }}"
          {{- if .Values.server.kubeconfigSecret }}
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/prelude/kubeconfig
              readOnly: true
          {{- end }}
        - name: cluster-authenticator
          image: "{{ .Values.clusterAuthenticator.image.repository }}:{{ .Values.clusterAuthenticator.image.tag }}"
          imagePullPolicy: {{ .Values.clusterAuthenticator.image.pullPolicy | default "Always" }}
          env:
            {{- if .Values.server.kubeconfigSecret }}
            - name: KUBECONFIG
              value: /etc/prelude/kubeconfig/kubeconfig
            {{- end }}
            - name: CLUSTER_POOL
              value: "{{ .Values.server.clusterPool }}"
            {{- if .Values.clusterAuthenticator.keycloakUrl }}
            - name: KEYCLOAK_URL
              value: "{{ .Values.clusterAuthenticator.keycloakUrl }}"
            {{- end }}
            {{- if not .Values.clusterAuthenticator.createHtpassSecret }}
            - name: CREATE_HTPASS_SECRET
              value: "false"
            {{- end }}
          {{- if .Values.server.kubeconfigSecret }}
          volumeMounts:
            - name: kubeconfig
              mountPath: /etc/prelude/kubeconfig
              readOnly: true
          {{- end }}
      {{- if .Values.server.kubeconfigSecret }}
      volumes:
        - name: kubeconfig
          secret:
            secretName: {{ .Values.server.kubeconfigSecret }}
      {{- end }}
